---
# Provision instances in AWS specific to the LAMP HA Proxy demo
- name: Provision instances in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - group_vars/all

  tasks:

  - name: Launch database instance
    ec2:
      image: "{{ ec2_image }}"
      instance_type: "{{ ec2_instance_type }}"
      key_name: "{{ ec2_keypair }}"
      region: "{{ ec2_region }}"
      wait: true
      count: "{{ ec2_dbserver_instance_count|int }}"
      instance_tags: "{'ansible_group':'dbservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
      vpc_subnet_id: "{{ ec2_subnet_id }}"
      assign_public_ip: yes
      group_id: "{{ ec2_security_group }}"  # or you can say 'default' here
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
